version: 1

services:
  - type: web
    name: chat-gpt
    dockerFilePath: Dockerfile
    port: 8000
    envVars:
      - key: APP_API_KEY
        value: ""
      - key: OPENAI_API_KEY
        value: ""
      - key: APP_MODE
        value: "OFFLINE"
    plan: free
